### ISSUE TITLE
Make tl:dr; shorter

### ISSUE THREAD

**Issue by RichardLitt** [Dotz0cat/walld#3]
> A wallpaper daemon. Walld automatically sets and changes the wallpaper. It sets the wallpaper through feh. It changes the wallpaper by default every 30 minutes. It also has a feature that grabs the 16 most prominent colors from the wallpaper that it has set. It then modifies the colors according to your preferences in the config file. After the colors have been modified, walld puts them in a file located at $HOME/.walld/colors. You can include this file in your .Xresources. Walld as a convenience then reloads your .Xresource with xrdb.

This is too long. I would add some paragaphs. Also, make it clear that it is only for one distro.

**Comment by Dotz0cat** [comment]
I have changed up that part of the description. I have also added a part saying it was mainly intended for Arch.

**Comment by RichardLitt** [comment]
Good work. Add a contributing section, and you're all set. :)
